### ISSUE TITLE
F# Issue: Problem reading assembly FSharp.Core.dll

### ISSUE THREAD

**Issue by avestura** [pjgpetecodes/dotnet5pi#3]
I have a problem running F# repl `dotnet fsi`:

```
pi@raspberrypi:~ $ dotnet fsi

Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> 

/home/pi/unknown(1,1): error FS0229: Error opening binary file '/opt/dotnet/sdk/5.0.100/FSharp/FSharp.Core.dll': Error reading/writing metadata for the F# compiled DLL '/opt/dotnet/sdk/5.0.100/FSharp/FSharp.Core.dll'. Was the DLL compiled with an earlier version of the F# compiler? (error: 'lookup_uniq in table istrings out of range, n = 16548, sizeof(tab) = 4565').



/home/pi/unknown(1,1): error FS3160: Problem reading assembly '/opt/dotnet/sdk/5.0.100/FSharp/FSharp.Core.dll': Processing of a script fragment has stopped because an exception has been raised

Exception by fsi.exe:
System.Exception: Error creating evaluation session: StopProcessingExn None
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at Microsoft.FSharp.Core.PrintfImpl.OneStepWithArg@501-1.Invoke(A arg1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 506
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2829
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 3155
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at Microsoft.FSharp.Control.LazyExtensions.Create@6615.Invoke() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 6615
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Sample.FSharp.Compiler.Interactive.Main.evaluateSession(String[] argv) in F:\workspace\_work\1\s\src\fsharp\fsi\fsimain.fs:line 269
```

Thanks for the great blog post and the installation script btw.

**Comment by pjgpetecodes** [comment]
Hey... Thanks for raising the issue @avestura... 

This is an issue in the ARM32 binaries sadly... https://github.com/dotnet/runtime/pull/45880 

The issue has been fixed but isn't due to be released until the next release - 5.0.102 (We're on 5.0.101 as of today)... 

https://github.com/dotnet/runtime/milestone/75

As soon as the next version is released, I'll update the script and you should be good to go!

**Comment by pjgpetecodes** [comment]
Also, thanks for the compliment... If you need anything else, let me know!

**Comment by avestura** [comment]
Thank you for looking into this.
